package app;

import java.util.ArrayList;

import io.javalin.http.Context;
import io.javalin.http.Handler;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;

/**
 * Example Index HTML class using Javalin
 * <p>
 * Generate a static HTML page using Javalin
 * by writing the raw HTML into a Java String object
 *
 * @author Timothy Wiley, 2023. email: timothy.wiley@rmit.edu.au
 * @author Santha Sumanasekara, 2021. email: santha.sumanasekara@rmit.edu.au
 * @author Halil Ali, 2024. email: halil.ali@rmit.edu.au
 */

public class PageIndex implements Handler {

    // URL of this page relative to http://localhost:7001/
    public static final String URL = "/";

    @Override
    public void handle(Context context) throws Exception {
        String html = "<html>\r\n";
        SaminJDBCConnection jdbc = new SaminJDBCConnection();

        html += "    <head>\r\n" + //
                "        <title>Home</title>\r\n" + //
                "        <link rel=\"stylesheet\" type=\"text/css\" href=\"common.css\">\r\n" + //
                "    </head>\r\n" + //
                "    <body>\r\n" + //
                "    <main>\r\n" +
                "        <div class=\"topnav\">\r\n" + //
                "            <a href=\"/\">\r\n" + //
                "            <img class='adapt-logo' src=\"logo.png\" alt=\"app logo\" id=\"logo\" width=\"260px\" height=\"30px\">\r\n"
                + //
                "            </a>\r\n" + //
                "            <div class=\"menu\">\r\n" + //
                "            <a href=\"/\">Home</a>\r\n" + //
                "            <a href=\"mission.html\">Mission</a>\r\n" + //
                "            <a href=\"page2A.html\">LGA 2019-2020</a>\r\n" + //
                "            <a href=\"page2B.html\">Regional Group</a>\r\n" + //
                "            <a href=\"page3A.html\">Similar LGAs</a>\r\n" + //
                "            <a href=\"page3B.html\">Change in Region</a>\r\n" + //
                "            </div>\r\n" + //
                "        </div>\r\n";
        html += "<div class='phone-menu'>" +
                "<a href=\"/\">Home</a>\r\n" + //
                "<p><a href=\"mission.html\">Mission</a>\r\n<p>" +
                "<p><a href=\"page2A.html\">LGA 2019-2020</a>\r\n<p>" +
                "<p><a href=\"page2B.html\">Regional Group</a>\r\n<p>" +
                "<p><a href=\"page3A.html\">Similar LGAs</a>\r\n<p>" +
                "<p><a href=\"page3B.html\">Change in Region</a>\r\n<p>" +
                "</div>";
        html += "        <div class='hor-center'>\r\n" + //
                "            <a href=\"mission.html\"> " +
                "            <img class='main-car-img' src=\"image1.png\" id=\"c1\" alt=\"image generated by openart.ai\">\r\n"
                + //
                "            </a>" +
                "        </div>\r\n" + //
                "        <div class=\"container-home adaptive-text\">\r\n" +
                "          <div class=\"container-house\">\r\n" +
                "            <div class=\"houseIcon\">\r\n" +
                "              <img src=\"house.png\">\r\n" +
                "            </div>\r\n" +
                "            <div class=\"barNumbers\">\r\n" +
                "              <div class=\"barNum1\">" + jdbc.getHousesByPeriod("2018-2019") + "</div>\r\n" +
                "              <div class=\"barNum2\">" + jdbc.getHousesByPeriod("2019-2020") + "</div>\r\n" +
                "            </div>\r\n" +
                "            <div class=\"houseBars\">\r\n" +
                "              <div class=\"containHouseBar\">\r\n" +
                "                <div class=\"container-houseBar\">" +
                "                  <div class=\"houseBar1\"></div>\r\n" +
                "                </div>\r\n" +
                "              </div>\r\n" +
                "              <div class=\"containHouseBar\">\r\n" +
                "                <div class=\"container-houseBar\">\r\n" +
                "                  <div class=\"houseBar2\"></div>\r\n" +
                "                </div>\r\n" +
                "              </div>\r\n" +
                "            </div>\r\n" +
                "            <div class=\"barPeriod\">\r\n" +
                "              <div class=\"barPeriod1\">2018-2019</div>\r\n" +
                "              <div class=\"barPeriod2\">2019-2020</div>\r\n" +
                "            </div>\r\n" +
                "          </div>\r\n" +
                "          <div class=\"container-house\">\r\n" +
                "            <div class=\"LGAicon\">\r\n" +
                "              <img src=\"LGAs.png\">\r\n" +
                "            </div>\r\n" +
                "            <div class=\"barNumbers\">\r\n" +
                "              <div class=\"barNum1\">" + jdbc.getLGAcountByPeriod("2018-2019") + "</div>\r\n" +
                "              <div class=\"barNum2\">" + jdbc.getLGAcountByPeriod("2019-2020") + "</div>\r\n" +
                "            </div>\r\n" +
                "            <div class=\"houseBars\">\r\n" +
                "              <div class=\"containHouseBar\">\r\n" +
                "                <div class=\"container-houseBar\">" +
                "                  <div class=\"LGAbar1\"></div>\r\n" +
                "                </div>\r\n" +
                "              </div>\r\n" +
                "              <div class=\"containHouseBar\">\r\n" +
                "                <div class=\"container-houseBar\">\r\n" +
                "                  <div class=\"LGAbar2\"></div>\r\n" +
                "                </div>\r\n" +
                "              </div>\r\n" +
                "            </div>\r\n" +
                "            <div class=\"barPeriod\">\r\n" +
                "              <div class=\"barPeriod1\">2018-2019</div>\r\n" +
                "              <div class=\"barPeriod2\">2019-2020</div>\r\n" +
                "            </div>\r\n" +
                "          </div>\r\n" +
                "        </div>\r\n" +
                "        </main>\r\n" +
                "        <script>\r\n" + //
                "            let currentPage = window.location.pathname.split(\"/\").pop();\r\n"
                + "if (currentPage === \"\") currentPage = \"/\";\r\n" + //
                "console.log(\"Current Page:\", currentPage);\r\n" + // check for script not working
                "            // Add 'active' class to the current page link\r\n" + //
                "            document.querySelectorAll('.menu a').forEach(link => {\r\n" + //
                "                if (link.getAttribute('href') === currentPage) {\r\n" + //
                "                    link.classList.add('active'); \r\n" + //
                "                }\r\n" + //
                "            });\r\n" + //
                "        </script>\r\n" + //
                "    <footer>\r\n" + //
                "        <a href=\"mission.html\">Contact | FAQ | Other Relevant Information</a>\r\n" + //
                "    </footer>\r\n" +
                "    </body>\r\n" + //
                "</html>";

        // DO NOT MODIFY THIS
        // Makes Javalin render the webpage
        context.html(html);
    }
}
